### ISSUE TITLE
The chromedriver version cannot be discovered

### ISSUE THREAD

**Issue by mecrayavcin** [mherrmann/helium#116]
Hi everyone. Could someone help me in this issue?

Code example

`from helium import *
from bs4 import BeautifulSoup
import time

url = "https//xxx/signup"

browser = start_chrome(url, headless=True)

time.sleep(5)        

soup = BeautifulSoup(browser.page_source, "html.parser")
print(soup)`

RESULT:

C:\Users\mecra\Desktop\Python>C:/Users/mecra/anaconda3/envs/heliumEnv/python.exe "c:/Users/mecra/Desktop/Python/Projects/Domain Backorder/Domain Checker/testo.py"
Unable to obtain driver using Selenium Manager: Selenium Manager failed for: C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json.
The chromedriver version cannot be discovered

DevTools listening on ws://127.0.0.1:59776/devtools/browser/dd78a565-bf91-4c62-b646-ebad89cc50b6
Traceback (most recent call last):
  File "c:\Users\mecra\Desktop\Python\Projects\Domain Backorder\Domain Checker\testo.py", line 8, in <module>
    browser = start_chrome(url, headless=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\__init__.py", line 78, in start_chrome
    return _get_api_impl().start_chrome_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\_impl\__init__.py", line 104, in start_chrome_impl
    return self._start(chrome_driver, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\_impl\__init__.py", line 139, in _start
    self.go_to_impl(url)
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\_impl\__init__.py", line 38, in f_decorated
    result = f(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\_impl\__init__.py", line 57, in f_decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\helium\_impl\__init__.py", line 146, in go_to_impl
    self.require_driver().get(url)
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mecra\anaconda3\envs\heliumEnv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=119.0.6045.160)
Stacktrace:
        GetHandleVerifier [0x00A172A3+45731]
        (No symbol) [0x009A2D51]
        (No symbol) [0x0089880D]
        (No symbol) [0x0089508E]
        (No symbol) [0x0088B4B2]
        (No symbol) [0x0088C34F]
        (No symbol) [0x0088B746]
        (No symbol) [0x0088AAF8]
        (No symbol) [0x0088AA9A]
        (No symbol) [0x008897F2]
        (No symbol) [0x00889ED8]
        (No symbol) [0x0089A5B3]
        (No symbol) [0x008FBD41]
        (No symbol) [0x008E7FDC]
        (No symbol) [0x008FB7A2]
        (No symbol) [0x008E7DD6]
        (No symbol) [0x008C31F6]
        (No symbol) [0x008C439D]
        GetHandleVerifier [0x00D20716+3229462]
        GetHandleVerifier [0x00D684C8+3523784]
        GetHandleVerifier [0x00D6214C+3498316]
        GetHandleVerifier [0x00AA1680+611968]
        (No symbol) [0x009ACCCC]
        (No symbol) [0x009A8DF8]
        (No symbol) [0x009A8F1D]
        (No symbol) [0x0099B2C7]
        BaseThreadInitThunk [0x75A87BA9+25]
        RtlInitializeExceptionChain [0x77DCBD2B+107]
        RtlClearBits [0x77DCBCAF+191]

**Comment by Mordojo** [comment]
Hi @mecrayavcin, i got the same issue when i tried to run my Robot framework test. See the error:

`[ WARN ] Unable to obtain driver using Selenium Manager: Selenium Manager failed for: /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json.
The chromedriver version cannot be discovered
| FAIL |
SeleniumManagerException: Message: Selenium Manager failed for: /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json.
The chromedriver version cannot be discovered`

I passed those requirements in the file requirements.txt as follow:
`selenium==4.9.1
robotframework==3.2.2
robotframework-seleniumlibrary==5.1.1
setuptools
RESTinstance`
